(tests
 (names
  test_core
  test_layouts
  test_events
  test_scenario_swap
  test_scenario_overview
  test_scenario_follow
  test_scenario_manage
  test_scenario_window
  test_scenario_tags
  test_scenario_layout
  test_scenario_scrolling
  test_scenario_ctl
  test_scenario_subscribe
  test_scenario_bind
  test_scenario_input
  test_scenario_warp
  test_scenario_scratchpad
  test_scenario_sticky
  test_scenario_swallow
  test_scenario_column
  test_scenario_label
  test_scenario_target
  test_scenario_spawn
  test_scenario_drag)
 (modules :standard \ fake_river harness)
 (libraries
  harness
  fake_river
  oxbow.core
  oxbow.layout
  oxbow.ops
  oxbow.ipc
  oxbow.ctl
  eio
  eio.unix
  yojson))

(library
 (name fake_river)
 (modules fake_river)
 (libraries oxbow.river wayland eio eio.unix logs unix))

(library
 (name harness)
 (modules harness)
 (libraries
  fake_river
  oxbow.runtime
  oxbow.ipc
  oxbow.ctl
  cmdliner
  wayland
  eio
  eio_main
  eio.unix
  unix
  logs
  yojson))
