(test
 (name test_core)
 (modules test_core)
 (libraries ocdwm.core ocdwm.ipc yojson))

(test
 (name test_layouts)
 (modules test_layouts)
 (libraries ocdwm.core ocdwm.layout))

(test
 (name test_events)
 (modules test_events)
 (libraries ocdwm.ipc yojson))

(library
 (name fake_river)
 (modules fake_river)
 (libraries ocdwm.river wayland eio eio.unix logs unix))

(test
 (name test_fake_river)
 (modules test_fake_river)
 (libraries
  fake_river
  ocdwm.runtime
  wayland
  eio
  eio_main
  eio.unix
  unix
  logs
  logs.fmt))
