(library
 (name ocdwm_protocol)
 (public_name ocdwm.protocol)
 (libraries wayland)
 (modules
  river_window_management_v1_client
  river_window_management_v1_proto
  river_xkb_bindings_v1_client
  river_xkb_bindings_v1_proto))

(rule
 (mode fallback)
 (targets
  river_window_management_v1_client.ml
  river_window_management_v1_proto.ml
  river_window_management_v1_server.ml)
 (deps river-window-management-v1.xml)
 (action
  (chdir
   %{workspace_root}/protocol
   (run wayland-scanner-ocaml %{deps}))))

(rule
 (mode fallback)
 (targets
  river_xkb_bindings_v1_client.ml
  river_xkb_bindings_v1_proto.ml
  river_xkb_bindings_v1_server.ml)
 (deps river-xkb-bindings-v1.xml)
 (action
  (chdir
   %{workspace_root}/protocol
   (run
    wayland-scanner-ocaml
    --open
    River_window_management_v1_client
    %{deps}))))
