(library
 (name oxbow_runtime)
 (public_name oxbow.runtime)
 (libraries
  oxbow.core
  oxbow.ipc
  oxbow.layout
  oxbow.state
  oxbow.ops
  oxbow.wire
  oxbow.river
  wayland
  eio
  eio.unix
  unix
  logs
  xkbcommon
  yojson
  ppx_yojson_conv_lib)
 (preprocess
  (pps ppx_yojson_conv landmarks-ppx --auto)))
